name: vittore
favicon: null
layout_spectrum: 0.4856330081764467
typography_spectrum: 0.7551019244613543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6cfe3'
    - '#f3f3f3'
    - '#000104'
    - '#f46810'
    - '#874826'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
